// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coabxobqegmtbbtkdozg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWJ4b2JxZWdtdGJidGtkb3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzQ5MTcsImV4cCI6MjA3Mzc1MDkxN30.Cz7oZdJ_7uacd4zwlHpWQQXeSJlgQ9Df7e4LgzK8yvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});